name: Netlify Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Deploy to Netlify
      uses: nwtgck/actions-netlify@v1
      with:
        publish-dir: ./build
        deploy-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
